<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\QueryBuilder;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get user events query with filtering by criteria
     *
     * @param User $user
     * @param array $criteria
     * @return \Doctrine\ORM\Query
     */
    public function getUserEventsQuery(User $user, array $criteria = [])
    {
        $queryBuilder = $this->createQueryBuilder('event')
            ->where('event.user = :user')
            ->setParameter('user', $user);

        $this->filterByDate($queryBuilder, $criteria);

        return $queryBuilder->getQuery();
    }

    /**
     * Add filter by date to event query
     *
     * @param QueryBuilder $builder
     * @param array $criteria
     * @return QueryBuilder
     */
    private function filterByDate(QueryBuilder $builder, array $criteria)
    {
        if (isset($criteria['date']))
        {
            $selectedDate = new \DateTime($criteria['date']);

            $builder->andWhere(
                $builder->expr()->not(
                    $builder->expr()->orX(
                        $builder->expr()->lt('event.timeEnd', ':startSelectedDate'),
                        $builder->expr()->gt('event.timeStart', ':endSelectedDate')
                    )
                )
            )
                ->setParameter('startSelectedDate', $selectedDate->format('Y-m-d 00:00:00'))
                ->setParameter('endSelectedDate', $selectedDate->format('Y-m-d 23:59:59'));
        }

        return $builder;
    }
}
