<?php

namespace AppBundle\Repository;

/**
 * EventStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
