<?php

namespace AppBundle\Repository;

/**
 * EventPriorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventPriorityRepository extends \Doctrine\ORM\EntityRepository
{
}
