<?php

namespace AppBundle\Repository;
use AppBundle\Entity\EventStatus;

/**
 * EventStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventStatusRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get status with code "new"
     *
     * @return null|object
     */
    public function getStatusNew()
    {
        return $this->findOneBy(['code' => EventStatus::STATUS_NEW]);
    }
}
