routing_user:
    resource: '@AppBundle/Resources/config/routing_user.yml'
    prefix: /api

routing_event:
    type: annotation
    resource: '@AppBundle/Controller/EventController.php'
    prefix: /api/event

routing_event_status:
    type: annotation
    resource: '@AppBundle/Controller/EventStatusController.php'
    prefix: /api/status

routing_event_priority:
    type: annotation
    resource: '@AppBundle/Controller/EventPriorityController.php'
    prefix: /api/priority
