profile:
    type: rest
    resource: AppBundle\Controller\RestProfileController

login:
    type: rest
    resource: AppBundle\Controller\RestLoginController

registration:
    type: rest
    resource: AppBundle\Controller\RestRegistrationController